### ISSUE TITLE
I got this TypeError. How to deal with this?? And is this command right? Please answer.

### ISSUE THREAD

**Issue by Eunhui** [r0ehre/GazePointHeatMap#1]
python gazeheatplot.py data.csv 1440 900 -a 0.6 -o result.png -b ./E
xample_Output/bg-image.png -n 200 -sd 33
Traceback (most recent call last):
  File "gazeheatplot.py", line 227, in <module>
    draw_heatmap(gaze_data, (display_width, display_height), alpha=alpha, savefilename=output_name, imagefile=background_image, gaussianwh=ngaussian, gaussiansd=sd)
  File "gazeheatplot.py", line 127, in draw_heatmap
    fig, ax = draw_display(dispsize, imagefile=imagefile)
  File "gazeheatplot.py", line 48, in draw_display
    screen[y:y + h, x:x + w, :] += img
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by TobiasRoeddiger** [comment]
This is a compatibility issue with Python versions.

**Comment by auto351** [comment]
Hi has any one fixed this issue we need to use PYTHON V3  on our server.

**Comment by akshay-salvi** [comment]
i want to get gaze data , how can i get that data?, i am using GazeML repository to fetch  gaze data , but i am not able to get that can you please tell me how to calculate gaze data(gaze points).

**Comment by akshay-salvi** [comment]
using theta and phi values can i able to calculate or iris_centre, eyeball_centre values,

**Comment by Eunhui** [comment]
> Hi has any one fixed this issue we need to use PYTHON V3 on our server.

you just enter this command "2to3 example.py" 
and then, switch all of "//" instead "/"
