### ISSUE TITLE
how to get the csv file

### ISSUE THREAD

**Issue by jjjjzzzzzz** [r0ehre/GazePointHeatMap#2]
Hi! Can you tell me how to get the axis of csv file?
I so appreciate if you can tell me that.

**Comment by TobiasRoeddiger** [comment]
Can you please clarify your question? What do you mean with axis of csv file?

**Comment by TobiasRoeddiger** [comment]
If you are looking for an examplatory input file please check the following link (data.csv)
https://github.com/TobiasRoeddiger/GazePointHeatMap/tree/master/Example%20Output

**Comment by TobiasRoeddiger** [comment]
Top left is 0,0.
